/* Body file for function tc_handler
 * Generated by TASTE on 2021-06-03 18:45:34
 * Provided interfaces : tc
 * Required interfaces : TC05, TC08, TC11, TC19, TC20
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 82735 50536 117490 72180
 * Timers              : 
 */
#include "tc_handler_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned tc_handler_initialized = 0;
void init_tc_handler(void)
{
   if (0 == tc_handler_initialized) {
      tc_handler_initialized = 1;
      // Call user code startup function
      extern void tc_handler_startup(void);
      tc_handler_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function tc_handler");
#endif
      tc_handler_initialized = 2;
   }
}
void tc_handler_tc()
{
   //  Directly call user code, no parameters to pass
   extern void tc_handler_PI_tc(void);
   tc_handler_PI_tc();
   // puts ("tc_handler_tc called");
}

