
/* Header file for function ST11TimeBasedScheduling in CPP language
 * Generated by TASTE on 2021-06-03 18:45:33
 * Context Parameters present : NO
 * Provided interfaces : EventActionTC11, TC11
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 151502 84993 191312 98105
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void st11timebasedscheduling_startup(void);

/* Provided interfaces */
void st11timebasedscheduling_PI_EventActionTC11( const asn1SccMessage * );
void st11timebasedscheduling_PI_TC11( const asn1SccMessage * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

