
/* Header file for function ST20ParameterService in CPP language
 * Generated by TASTE on 2021-06-03 18:45:33
 * Context Parameters present : NO
 * Provided interfaces : EventActionTC20, TC20
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 151502 117062 190680 129859
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void st20parameterservice_startup(void);

/* Provided interfaces */
void st20parameterservice_PI_EventActionTC20( const asn1SccMessage * );
void st20parameterservice_PI_TC20( const asn1SccMessage * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

