/* Header file for function ST11TimeBasedScheduling in CPP language
 * Generated by TASTE on 2021-06-03 18:45:33
 * Context Parameters present : NO
 * Provided interfaces : EventActionTC11, TC11
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 151502 84993 191312 98105
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#include "st11timebasedscheduling.h"

// Function initialization - calls user startup code of all dependent functions
void init_st11timebasedscheduling(void);


/* Provided interfaces */
void st11timebasedscheduling_EventActionTC11
      (const char *IN_message, size_t IN_message_len);

void st11timebasedscheduling_TC11
      (const char *IN_message, size_t IN_message_len);


#ifdef __cplusplus
}
#endif

