/* Body file for function ST05EventReport
 * Generated by TASTE on 2021-06-03 18:45:33
 * Provided interfaces : EventActionTC05, TC05
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 151185 50237 191312 64771
 * Timers              : 
 */
#include "st05eventreport_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned st05eventreport_initialized = 0;
void init_st05eventreport(void)
{
   if (0 == st05eventreport_initialized) {
      st05eventreport_initialized = 1;
      // Call user code startup function
      extern void st05eventreport_startup(void);
      st05eventreport_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function ST05EventReport");
#endif
      st05eventreport_initialized = 2;
   }
}
void st05eventreport_EventActionTC05
      (const char *IN_message, size_t IN_message_len)

{

   static asn1SccMessage IN_MESSAGE;
#ifdef __unix__
   asn1SccMessage_Initialize(&IN_MESSAGE);
#endif
   if (0 != Decode_NATIVE_Message (&IN_MESSAGE, (void *)IN_message, IN_message_len)) {
      #ifdef __unix__
         puts("Error decoding Message in function ST05EventReport_EventActionTC05");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void st05eventreport_PI_EventActionTC05
      (const asn1SccMessage *);




   // Call user code
   st05eventreport_PI_EventActionTC05 (&IN_MESSAGE);

}
void st05eventreport_TC05
      (const char *IN_message, size_t IN_message_len)

{

   static asn1SccMessage IN_MESSAGE;
#ifdef __unix__
   asn1SccMessage_Initialize(&IN_MESSAGE);
#endif
   if (0 != Decode_NATIVE_Message (&IN_MESSAGE, (void *)IN_message, IN_message_len)) {
      #ifdef __unix__
         puts("Error decoding Message in function ST05EventReport_TC05");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void st05eventreport_PI_TC05
      (const asn1SccMessage *);




   // Call user code
   st05eventreport_PI_TC05 (&IN_MESSAGE);

}

