/* Body file for function ST19EventAction
 * Generated by TASTE on 2021-06-03 18:45:33
 * Provided interfaces : TC19
 * Required interfaces : EventActionTC05, EventActionTC08, EventActionTC11, EventActionTC20
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 151502 101264 190838 113113
 * Timers              : 
 */
#include "st19eventaction_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned st19eventaction_initialized = 0;
void init_st19eventaction(void)
{
   if (0 == st19eventaction_initialized) {
      st19eventaction_initialized = 1;
      // Call user code startup function
      extern void st19eventaction_startup(void);
      st19eventaction_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function ST19EventAction");
#endif
      st19eventaction_initialized = 2;
   }
}
void st19eventaction_TC19
      (const char *IN_message, size_t IN_message_len)

{

   static asn1SccMessage IN_MESSAGE;
#ifdef __unix__
   asn1SccMessage_Initialize(&IN_MESSAGE);
#endif
   if (0 != Decode_NATIVE_Message (&IN_MESSAGE, (void *)IN_message, IN_message_len)) {
      #ifdef __unix__
         puts("Error decoding Message in function ST19EventAction_TC19");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void st19eventaction_PI_TC19
      (const asn1SccMessage *);




   // Call user code
   st19eventaction_PI_TC19 (&IN_MESSAGE);

}

