
/* Header file for function ST05EventReport in CPP language
 * Generated by TASTE on 2021-06-03 18:45:33
 * Context Parameters present : NO
 * Provided interfaces : EventActionTC05, TC05
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 151185 50237 191312 64771
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void st05eventreport_startup(void);

/* Provided interfaces */
void st05eventreport_PI_EventActionTC05( const asn1SccMessage * );
void st05eventreport_PI_TC05( const asn1SccMessage * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

