#ifndef __PRINTTYPESASASN1_H__
#define __PRINTTYPESASASN1_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintASN1MyInteger(const char *paramName, const asn1SccMyInteger *pData);
void PrintASN1UInt8(const char *paramName, const asn1SccUInt8 *pData);
void PrintASN1UInt16(const char *paramName, const asn1SccUInt16 *pData);
void PrintASN1Packet(const char *paramName, const asn1SccPacket *pData);
void PrintASN1Message(const char *paramName, const asn1SccMessage *pData);
void PrintASN1EventOccured(const char *paramName, const asn1SccEventOccured *pData);
void PrintASN1AcceptanceErrorOccured(const char *paramName, const asn1SccAcceptanceErrorOccured *pData);
void PrintASN1RoutingErrorType(const char *paramName, const asn1SccRoutingErrorType *pData);
void PrintASN1ExecutionStartErrorType(const char *paramName, const asn1SccExecutionStartErrorType *pData);
void PrintASN1ExecutionProgressErrorType(const char *paramName, const asn1SccExecutionProgressErrorType *pData);
void PrintASN1ExecutionCompletionErrorType(const char *paramName, const asn1SccExecutionCompletionErrorType *pData);
void PrintASN1T_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintASN1T_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintASN1T_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintASN1T_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintASN1T_Boolean(const char *paramName, const asn1SccT_Boolean *pData);
void PrintASN1T_Null_Record(const char *paramName, const asn1SccT_Null_Record *pData);

#ifdef __cplusplus
}
#endif

#endif
