
/* Header file for function ST08FunctionManagement in CPP language
 * Generated by TASTE on 2021-06-03 18:45:33
 * Context Parameters present : NO
 * Provided interfaces : EventActionTC08, TC08
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 151344 68405 191312 81201
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void st08functionmanagement_startup(void);

/* Provided interfaces */
void st08functionmanagement_PI_EventActionTC08( const asn1SccMessage * );
void st08functionmanagement_PI_TC08( const asn1SccMessage * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif

