
/* Header file for function ST19EventAction in CPP language
 * Generated by TASTE on 2021-06-03 18:45:33
 * Context Parameters present : NO
 * Provided interfaces : TC19
 * Required interfaces : EventActionTC05, EventActionTC08, EventActionTC11, EventActionTC20
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 151502 101264 190838 113113
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void st19eventaction_startup(void);

/* Provided interfaces */
void st19eventaction_PI_TC19( const asn1SccMessage * );

/* Required interfaces */
extern void st19eventaction_RI_EventActionTC05( const asn1SccMessage * );
extern void st19eventaction_RI_EventActionTC08( const asn1SccMessage * );
extern void st19eventaction_RI_EventActionTC11( const asn1SccMessage * );
extern void st19eventaction_RI_EventActionTC20( const asn1SccMessage * );


#ifdef __cplusplus
}
#endif

